// This file is auto-generated by @udibo/juniper/build
// Do not edit this file directly.

import { Client } from "@udibo/juniper/client";

export const client = new Client({
  path: "/",
  main: await import("./routes/main.tsx"),
  index: () => import("./routes/index.tsx"),
});
