// This file is auto-generated by @udibo/juniper/build
// Do not edit this file directly.

import { createServer } from "@udibo/juniper/server";

import { client } from "./main.tsx";

export const server = createServer(import.meta.url, client, {
  path: "/",
  main: await import("./routes/main.ts"),
  children: [
    {
      path: "api",
      main: await import("./routes/api/main.ts"),
    },
    {
      path: "auth",
      main: await import("./routes/auth/main.ts"),
    },
    {
      path: "login",
      main: await import("./routes/login.ts"),
    },
    {
      path: "logout",
      main: await import("./routes/logout.ts"),
    },
    {
      path: "oauth2",
      main: await import("./routes/oauth2/main.ts"),
    },
  ],
});

if (import.meta.main) {
  Deno.serve(server.fetch);
}
