/**
 * AI-ready docs gate and generator.
 *
 * `llms.txt` is the hand-written index; `llms-full.txt` is the whole corpus
 * concatenated into one file for a single agent fetch. This script keeps the
 * two honest:
 *
 * - `pnpm llms:generate` regenerates `llms-full.txt` from the pages `llms.txt`
 *   lists, in index order.
 * - `pnpm llms:check` (part of `pnpm check`) fails when a docs, example, or
 *   template page is not linked from `llms.txt`, when any link in `llms.txt`
 *   or `README.md` does not resolve, or when `llms-full.txt` is stale.
 *
 * The generation is deterministic: page order is the order of links in the
 * `## Docs` section of `llms.txt`, and nothing else varies.
 *
 * @module
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { isMain } from "./_main.ts";

const INDEX = "llms.txt";
const FULL = "llms-full.txt";
const UNINDEXED = new Set(["docs/migration-tests.md"]);
const LINK = /\[[^\]]*\]\(([^)]+)\)/g;

function localLinks(markdown: string): string[] {
  const targets: string[] = [];
  for (const match of markdown.matchAll(LINK)) {
    const target = match[1]!.trim();
    if (/^[a-z]+:/i.test(target) || target.startsWith("#")) continue;
    targets.push(target);
  }
  return targets;
}

function stripAnchor(target: string): string {
  const hash = target.indexOf("#");
  return hash === -1 ? target : target.slice(0, hash);
}

function docsSectionLinks(index: string): string[] {
  const lines = index.split("\n");
  const start = lines.findIndex((line) => line.trim() === "## Docs");
  if (start === -1) throw new Error("llms.txt has no `## Docs` section.");
  let end = start + 1;
  while (end < lines.length && !lines[end]!.startsWith("## ")) end++;
  return localLinks(lines.slice(start, end).join("\n")).map(stripAnchor);
}

function headerBlock(index: string): string {
  const marker = index.indexOf("\n## Docs");
  if (marker === -1) throw new Error("llms.txt has no `## Docs` section.");
  return index.slice(0, marker).trimEnd();
}

function walk(
  dir: string,
  prefix: string,
  keep: (name: string) => boolean,
  found: string[],
): void {
  if (!existsSync(dir)) return;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.name === "node_modules") continue;
    if (entry.isDirectory()) {
      walk(join(dir, entry.name), `${prefix}${entry.name}/`, keep, found);
    } else if (keep(entry.name)) {
      found.push(`${prefix}${entry.name}`);
    }
  }
}

function corpusFiles(root: string): string[] {
  const found: string[] = [];
  walk(join(root, "docs"), "docs/", (name) => name.endsWith(".md"), found);
  for (const dir of ["examples", "templates"]) {
    walk(join(root, dir), `${dir}/`, (name) => name === "README.md", found);
  }
  return found.filter((file) => !UNINDEXED.has(file)).sort();
}

/** Renders `llms-full.txt` for the `llms.txt` index text, reading pages from `root`. */
export function render(root: string, index: string): string {
  const order = docsSectionLinks(index);
  const parts = [headerBlock(index)];
  parts.push(
    "## Full documentation\n\n" +
      "Every page linked from the `## Docs` section of `llms.txt`, concatenated " +
      "in index order for a single-fetch corpus. Generated by " +
      "`pnpm llms:generate`; do not edit by hand.",
  );
  for (const source of order) {
    const body = readFileSync(resolve(root, source), "utf8")
      .trim()
      .replace(LINK, (match, target: string) => {
        if (/^[a-z]+:/i.test(target)) return match;
        const url = new URL(
          target,
          `https://github.com/udibo/oauth2/blob/main/${source}`,
        );
        return match.replace(`(${target})`, `(${url.href})`);
      });
    parts.push(`<!-- llms-full:source=${source} -->\n\n${body}`);
  }
  return parts.join("\n\n---\n\n") + "\n";
}

/** Lists what is wrong with the index, its links, and the generated corpus. */
export function findProblems(root: string): string[] {
  const failures: string[] = [];
  const index = readFileSync(resolve(root, INDEX), "utf8");

  const indexed = new Set(localLinks(index).map(stripAnchor));
  for (const file of corpusFiles(root)) {
    if (!indexed.has(file)) failures.push(`not linked from ${INDEX}: ${file}`);
  }

  for (const source of [INDEX, "README.md"]) {
    const markdown = readFileSync(resolve(root, source), "utf8");
    for (const target of localLinks(markdown)) {
      const path = stripAnchor(target);
      if (path && !existsSync(resolve(root, dirname(source), path))) {
        failures.push(`dead link in ${source}: ${target}`);
      }
    }
  }

  const expected = render(root, index);
  const fullPath = resolve(root, FULL);
  if (!existsSync(fullPath)) {
    failures.push(`${FULL} is missing; run \`pnpm llms:generate\``);
  } else if (readFileSync(fullPath, "utf8") !== expected) {
    failures.push(`${FULL} is stale; run \`pnpm llms:generate\``);
  }
  return failures;
}

function main(args: string[]): number {
  const root = resolve(fileURLToPath(new URL("../", import.meta.url)));
  if (args.includes("--check")) {
    const failures = findProblems(root);
    if (failures.length > 0) {
      console.error(failures.map((line) => `  - ${line}`).join("\n"));
      console.error(`\nllms: ${failures.length} problem(s).`);
      return 1;
    }
    const index = readFileSync(resolve(root, INDEX), "utf8");
    console.log(
      `llms: ${new Set(localLinks(index).map(stripAnchor)).size} indexed links, ${FULL} current.`,
    );
    return 0;
  }
  const index = readFileSync(resolve(root, INDEX), "utf8");
  writeFileSync(resolve(root, FULL), render(root, index));
  console.log(`llms: wrote ${FULL}.`);
  return 0;
}

if (isMain(import.meta.url)) {
  process.exit(main(process.argv.slice(2)));
}
