/**
 * AI-ready docs gate and generator.
 *
 * `llms.txt` is the hand-written index; `llms-full.txt` is the whole corpus
 * concatenated into one file for a single agent fetch. This script keeps the
 * two honest:
 *
 * - `deno task llms:generate` regenerates `llms-full.txt` from the pages
 *   `llms.txt` lists, in index order.
 * - `deno task llms:check` (wired into `deno task check`, so CI runs it) fails
 *   when a docs, example, or template page is not linked from `llms.txt`, when
 *   any link in `llms.txt` or `README.md` does not resolve, or when
 *   `llms-full.txt` is stale.
 *
 * The generation is deterministic — page order is the order of links in the
 * `## Docs` section of `llms.txt`, and nothing else varies — so the committed
 * file and a fresh regeneration are byte-for-byte identical or the check fails.
 *
 * @module
 */

const packageDir = new URL("../", import.meta.url);
const INDEX = "llms.txt";
const FULL = "llms-full.txt";

const LINK = /\[[^\]]*\]\(([^)]+)\)/g;

function localLinks(markdown: string): string[] {
  const targets: string[] = [];
  for (const match of markdown.matchAll(LINK)) {
    const target = match[1].trim();
    if (/^[a-z]+:/i.test(target) || target.startsWith("#")) continue;
    targets.push(target);
  }
  return targets;
}

function stripAnchor(target: string): string {
  const hash = target.indexOf("#");
  return hash === -1 ? target : target.slice(0, hash);
}

function docsSectionLinks(index: string): string[] {
  const lines = index.split("\n");
  const start = lines.findIndex((line) => line.trim() === "## Docs");
  if (start === -1) throw new Error("llms.txt has no `## Docs` section.");
  let end = start + 1;
  while (end < lines.length && !lines[end].startsWith("## ")) end++;
  return localLinks(lines.slice(start, end).join("\n")).map(stripAnchor);
}

function headerBlock(index: string): string {
  const marker = index.indexOf("\n## Docs");
  if (marker === -1) throw new Error("llms.txt has no `## Docs` section.");
  return index.slice(0, marker).trimEnd();
}

async function walk(
  dir: URL,
  prefix: string,
  keep: (name: string) => boolean,
  found: string[],
): Promise<void> {
  for await (const entry of Deno.readDir(dir)) {
    if (entry.isDirectory) {
      await walk(
        new URL(`${entry.name}/`, dir),
        `${prefix}${entry.name}/`,
        keep,
        found,
      );
    } else if (keep(entry.name)) {
      found.push(`${prefix}${entry.name}`);
    }
  }
}

async function corpusFiles(): Promise<string[]> {
  const found: string[] = [];
  await walk(
    new URL("docs/", packageDir),
    "docs/",
    (n) => n.endsWith(".md"),
    found,
  );
  const isReadme = (n: string) => n === "README.md";
  for (const root of ["examples/", "templates/"]) {
    await walk(new URL(root, packageDir), root, isReadme, found);
  }
  return found.sort();
}

async function render(index: string): Promise<string> {
  const order = docsSectionLinks(index);
  const parts = [headerBlock(index)];
  parts.push(
    "## Full documentation\n\n" +
      "Every page linked from the `## Docs` section of `llms.txt`, concatenated " +
      "in index order for a single-fetch corpus. Generated by " +
      "`deno task llms:generate`; do not edit by hand.",
  );
  for (const source of order) {
    const body = (await Deno.readTextFile(new URL(source, packageDir))).trim()
      .replace(LINK, (match, target: string) => {
        if (/^[a-z]+:/i.test(target)) return match;
        const url = new URL(
          target,
          `https://github.com/udibo/oauth2/blob/main/${source}`,
        );
        return match.replace(`(${target})`, `(${url.href})`);
      });
    parts.push(`<!-- llms-full:source=${source} -->\n\n${body}`);
  }
  return parts.join("\n\n---\n\n") + "\n";
}

async function resolves(source: string, target: string): Promise<boolean> {
  try {
    await Deno.stat(new URL(target, new URL(source, packageDir)));
    return true;
  } catch {
    return false;
  }
}

async function check(index: string): Promise<number> {
  const failures: string[] = [];

  const indexed = new Set(localLinks(index).map(stripAnchor));
  for (const file of await corpusFiles()) {
    if (!indexed.has(file)) {
      failures.push(`not linked from ${INDEX}: ${file}`);
    }
  }

  for (const source of [INDEX, "README.md"]) {
    const markdown = await Deno.readTextFile(new URL(source, packageDir));
    for (const target of localLinks(markdown)) {
      const path = stripAnchor(target);
      if (path && !(await resolves(source, path))) {
        failures.push(`dead link in ${source}: ${target}`);
      }
    }
  }

  const expected = await render(index);
  let actual: string | null = null;
  try {
    actual = await Deno.readTextFile(new URL(FULL, packageDir));
  } catch {
    actual = null;
  }
  if (actual !== expected) {
    failures.push(
      actual === null
        ? `${FULL} is missing; run \`deno task llms:generate\``
        : `${FULL} is stale; run \`deno task llms:generate\``,
    );
  }

  if (failures.length > 0) {
    console.error(failures.map((line) => `  - ${line}`).join("\n"));
    console.error(`\nllms: ${failures.length} problem(s).`);
    return 1;
  }
  console.log(
    `llms: ${indexed.size} indexed links, ${FULL} current.`,
  );
  return 0;
}

const index = await Deno.readTextFile(new URL(INDEX, packageDir));

if (Deno.args.includes("--check")) {
  Deno.exit(await check(index));
} else {
  await Deno.writeTextFile(new URL(FULL, packageDir), await render(index));
  console.log(`llms: wrote ${FULL}.`);
}
