/**
 * Regenerates — or verifies the freshness of —
 * `src/server/public-suffix/rules.ts` from publicsuffix.org.
 *
 * ```sh
 * pnpm psl:update   # rewrite the bundled snapshot from upstream
 * pnpm psl:check    # fail when the bundled snapshot has drifted
 * ```
 *
 * `check` is what the scheduled CI job runs. It compares the *parsed rules*
 * rather than the raw file, so an upstream comment or reordering does not fail
 * the gate — only a rule appearing, disappearing, or changing does.
 *
 * @module
 */

import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const SOURCE_URL = "https://publicsuffix.org/list/public_suffix_list.dat";
const ROOT = fileURLToPath(new URL("../", import.meta.url));
const RULES_PATH = fileURLToPath(
  new URL("../src/server/public-suffix/rules.ts", import.meta.url),
);

interface Snapshot {
  rules: string[];
  sha256: string;
}

function toAscii(name: string): string {
  const url = URL.parse(`https://${name}`);
  if (!url) throw new Error(`Public suffix rule is not a valid host: ${name}`);
  return url.hostname;
}

function normalizeRule(text: string): string {
  const exception = text.startsWith("!");
  const body = exception ? text.slice(1) : text;
  const wildcard = body.startsWith("*.");
  const core = wildcard ? body.slice(2) : body;
  const ascii = /[^!-~]/.test(core) ? toAscii(core) : core.toLowerCase();
  return `${exception ? "!" : ""}${wildcard ? "*." : ""}${ascii}`;
}

function parseRules(raw: string): string[] {
  const rules: string[] = [];
  let inSection = false;
  for (const line of raw.split("\n")) {
    const text = line.trim();
    if (text === "// ===BEGIN ICANN DOMAINS===") inSection = true;
    else if (text === "// ===BEGIN PRIVATE DOMAINS===") inSection = true;
    else if (text === "// ===END ICANN DOMAINS===") inSection = false;
    else if (text === "// ===END PRIVATE DOMAINS===") inSection = false;
    if (!inSection || text === "" || text.startsWith("//")) continue;
    rules.push(normalizeRule(text));
  }
  if (rules.length < 5000) {
    throw new Error(
      `Only ${rules.length} rules parsed from ${SOURCE_URL}; refusing to ` +
        `generate a snapshot from what looks like a truncated or changed file.`,
    );
  }
  return rules;
}

function sha256(raw: string): string {
  return createHash("sha256").update(raw).digest("hex");
}

async function fetchSnapshot(): Promise<Snapshot> {
  const response = await fetch(SOURCE_URL);
  if (!response.ok) {
    throw new Error(`GET ${SOURCE_URL} responded ${response.status}`);
  }
  const raw = await response.text();
  return { rules: parseRules(raw), sha256: sha256(raw) };
}

function render(snapshot: Snapshot, retrieved: string): string {
  return `/**
 * The ICANN + private Public Suffix List, generated by
 * \`pnpm psl:update\`. **Do not edit by hand.**
 *
 * @module
 */

/** Where the snapshot came from, when, and what it hashed to. */
export const publicSuffixListInfo = {
  /** The upstream file this snapshot was generated from. */
  source: ${JSON.stringify(SOURCE_URL)},
  /** The date the snapshot was taken, as \`YYYY-MM-DD\`. */
  retrieved: ${JSON.stringify(retrieved)},
  /** SHA-256 of the upstream file, hex encoded. */
  sha256: ${JSON.stringify(snapshot.sha256)},
  /** How many rules the snapshot holds. */
  ruleCount: ${snapshot.rules.length},
} as const;

/**
 * Every rule, newline separated and punycode encoded, exactly as
 * publicsuffix.org writes them (\`!\` for an exception rule, a leading \`*.\`
 * for a wildcard rule).
 */
export const PUBLIC_SUFFIX_RULES = ${JSON.stringify(snapshot.rules.join("\n"))};
`;
}

function format(path: string): void {
  const oxfmt = fileURLToPath(
    new URL("../node_modules/oxfmt/bin/oxfmt", import.meta.url),
  );
  const result = spawnSync(process.execPath, [oxfmt, path], {
    cwd: ROOT,
    stdio: ["ignore", "ignore", "inherit"],
  });
  if (result.status !== 0) throw new Error(`oxfmt failed on ${path}`);
}

async function update(): Promise<void> {
  const snapshot = await fetchSnapshot();
  const retrieved = new Date().toISOString().slice(0, 10);
  writeFileSync(RULES_PATH, render(snapshot, retrieved));
  format(RULES_PATH);
  console.log(
    `psl: wrote ${snapshot.rules.length} rules from ${SOURCE_URL} ` +
      `(${retrieved}, sha256 ${snapshot.sha256.slice(0, 12)}…).`,
  );
}

async function check(): Promise<void> {
  const [{ PUBLIC_SUFFIX_RULES, publicSuffixListInfo }, upstream] =
    await Promise.all([
      import("../src/server/public-suffix/rules.ts"),
      fetchSnapshot(),
    ]);

  const bundled = new Set(PUBLIC_SUFFIX_RULES.split("\n"));
  const fresh = new Set(upstream.rules);
  const added = upstream.rules.filter((rule) => !bundled.has(rule));
  const removed = [...bundled].filter((rule) => !fresh.has(rule));

  if (added.length === 0 && removed.length === 0) {
    console.log(
      `psl: bundled snapshot (${publicSuffixListInfo.retrieved}) matches ` +
        `${SOURCE_URL} — ${bundled.size} rules.`,
    );
    return;
  }

  const sample = (rules: string[]) =>
    rules.slice(0, 20).join(", ") + (rules.length > 20 ? ", …" : "");
  console.error(
    `psl: the bundled Public Suffix List has drifted from ${SOURCE_URL}.\n` +
      `  bundled: ${publicSuffixListInfo.retrieved}, ${bundled.size} rules\n` +
      `  upstream: ${fresh.size} rules\n` +
      `  ${added.length} added: ${sample(added)}\n` +
      `  ${removed.length} removed: ${sample(removed)}\n` +
      `Run \`pnpm psl:update\` and commit the result.`,
  );
  process.exit(1);
}

if (process.argv.slice(2).includes("--check")) {
  await check();
} else {
  await update();
}
