// This file is auto-generated by @udibo/juniper/build
// Do not edit this file directly.

import { Client } from "@udibo/juniper/client";

export const client = new Client({
  path: "/",
  main: await import("./routes/main.tsx"),
  index: () => import("./routes/index.tsx"),
  children: [
    {
      path: "login",
      main: () => import("./routes/login.tsx"),
      server: {
        loader: true,
        action: true,
      },
    },
    {
      path: "profile",
      main: () => import("./routes/profile.tsx"),
    },
    {
      path: "signup",
      main: () => import("./routes/signup.tsx"),
      server: {
        loader: true,
        action: true,
      },
    },
  ],
});
